variable "username" {}
variable "int" {}
variable "int_desc" {}
variable "bw" {}
variable "project_id" {}
variable "metro_code" {}
variable "sec_metro_code" {}
variable "vnf_asn" {}
variable "neighbor_desc_pri" {}
variable "neighbor_desc_sec" {}
variable "pri_vc" {}
variable "sec_vc" {}
variable "emails" {}
variable "connection_name" {}